### ISSUE TITLE
(Beta 3) Information seems to constantly refresh

### ISSUE THREAD

**Issue by JoramD0** [RobertFrydenlund/SpotifyPlugin#22]
In beta 3 the information seems to refresh every ~10 seconds. This might be an issue on the skins end but I am not sure.

```
23:24:09 Monday, July 23, 2018
SpotifyPlugin version 2.1.6.0
Culture: en-US
OSVersion: Microsoft Windows NT 10.0.17134.0
----
 The remote server returned an error: (404) Not Found.
----
    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at SpotifyPlugin.AlbumArt.GetAlbumImage(Int32 resolution, String filePath) (Monstercat-Visualizer\visualizer.ini - [MeasureProgressPrecent])
``` 
```
(Fetch error) The operation timed out  (ErrorCode=12002) (Monstercat-Visualizer\Song Information\Cover\Cover.ini - [MeasureWebParser])
```
These errors were posted to the log.

**Comment by RobertFrydenlund** [comment]
I am aware of this. The WebApi keeps returning empty responses once in a while, and it detects that as album changes. Then it tries downloading the album for an empty URI and it fails. You can safely ignore the error for now. This will fix itself when i fix the issue with empty responses.

**Comment by RobertFrydenlund** [comment]
The second error seems related to this issue https://github.com/MarcoPixel/Monstercat-Visualizer/issues/197

**Comment by MarcoPixel** [comment]
@RobertFrydenlund FYI, the issue you've mentioned is probably affecting the WebNowPlaying plugin from @tjhrulz. 😉

**Comment by RobertFrydenlund** [comment]
@MarcoPixel Still happens with only WebNowPlaying installed. 
Steps I did to reproduce:
- Delete rainmeter plugin folder
- Clean install Monstercat Visualizer
- Uncheck SpotifyPlugin and Chameleon(To avoid the error spam from not having a 0.png)
```
ERRO (16:53:47.588) monstercat-visualizer\Song Information\Left.ini - [MeasureWebParser]: (Fetch error) The operation timed out  (ErrorCode=12002)
ERRO (16:53:47.619) monstercat-visualizer\visualizer.ini - [MeasureWebParser]: (Fetch error) The operation timed out  (ErrorCode=12002)
ERRO (16:53:47.779) monstercat-visualizer\visualizer.ini - [MeasureWebParser]: (Fetch error) The operation timed out  (ErrorCode=12002)
ERRO (16:54:57.200) monstercat-visualizer\visualizer.ini - [MeasureWebParser]: (Fetch error) The operation timed out  (ErrorCode=12002)
ERRO (16:56:06.685) monstercat-visualizer\visualizer.ini - [MeasureWebParser]: (Fetch error) The operation timed out  (ErrorCode=12002)
ERRO (16:56:49.446) monstercat-visualizer\Song Information\Cover\Cover.ini - [MeasureWebParser]: (Fetch error) The operation timed out  (ErrorCode=12002)
ERRO (16:56:49.593) monstercat-visualizer\Song Information\Left.ini - [MeasureWebParser]: (Fetch error) The operation timed out  (ErrorCode=12002)
ERRO (16:57:16.077) monstercat-visualizer\visualizer.ini - [MeasureWebParser]: (Fetch error) The operation timed out  (ErrorCode=12002)
ERRO (16:58:25.454) monstercat-visualizer\visualizer.ini - [MeasureWebParser]: (Fetch error) The operation timed out  (ErrorCode=12002)
```

**Comment by RobertFrydenlund** [comment]
@MarcoPixel Yeah, my bad, I just keep thinking I'm the only third party involved 😄
Opened an issue regarding this at https://github.com/tjhrulz/WebNowPlaying/issues/17. Will close this issue, as the 404 error is a side effect of #19.
